sonar.projectKey=Mostafijur-1_Focused
sonar.projectName=Focused
sonar.sourceEncoding=UTF-8
sonar.sources=apps/web/src,design-system
sonar.tests=apps/web/tests,apps/web/e2e
sonar.test.inclusions=apps/web/tests/**/*,apps/web/e2e/**/*
sonar.exclusions=**/.next/**,**/node_modules/**,**/coverage/**,**/*.config.*,prisma/migrations/**
sonar.coverage.exclusions=apps/web/src/app/**
sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info
sonar.typescript.tsconfigPaths=apps/web/tsconfig.json
