import type { NotificationCategory } from "@/features/notifications/domain/notification-types";
import type { Locale } from "@/i18n/config";

export function getNotificationCopy(locale: Locale) {
  return locale === "bn-BD" ? bn : en;
}

const bn = {
  eyebrow: "শান্তভাবে, ঠিক সময়ে",
  title: "Notification ও Reminder",
  subtitle:
    "যেটি এখন দরকার, শুধু সেটিই পান। ব্যক্তিগত তথ্য lock screen-এ দেখানো হয় না।",
  refresh: "আবার দেখুন",
  unread: (count: number) => `${count}টি না-পড়া`,
  activeReminders: "সক্রিয় Reminder",
  pushDevices: "Web Push ডিভাইস",
  quietHours: "নীরব সময়",
  inboxTitle: "Notification inbox",
  inboxDescription: "সাম্প্রতিক গুরুত্বপূর্ণ আপডেট—অপ্রয়োজনীয় শব্দ ছাড়া।",
  inboxEmpty:
    "এখন কোনো Notification নেই। গুরুত্বপূর্ণ কিছু এলে এখানে দেখা যাবে।",
  markRead: "পড়া হয়েছে",
  markUnread: "না-পড়া রাখুন",
  archive: "সরিয়ে রাখুন",
  remindersTitle: "আপনার Reminder",
  remindersDescription: "একবারের বা নিয়মিত Reminder তৈরি ও নিয়ন্ত্রণ করুন।",
  remindersEmpty:
    "এখনো কোনো Reminder নেই। ছোট একটি পরবর্তী পদক্ষেপ দিয়ে শুরু করুন।",
  addReminder: "Reminder যোগ করুন",
  editReminder: "Reminder সম্পাদনা",
  titleLabel: "কী মনে করিয়ে দেব?",
  titlePlaceholder: "যেমন: আজকের প্রধান কাজ শুরু করুন",
  noteLabel: "বিস্তারিত (ঐচ্ছিক)",
  notePlaceholder: "এই লেখা শুধু app-এর ভেতরে দেখা যাবে",
  frequency: "সময়ধারা",
  once: "একবার",
  daily: "প্রতিদিন",
  weekly: "নির্বাচিত দিন",
  date: "তারিখ",
  time: "সময়",
  interval: "কত দিন পরপর",
  channels: "কোথায় জানাব",
  inApp: "App-এর ভেতরে",
  webPush: "Web Push",
  save: "সংরক্ষণ করুন",
  saving: "সংরক্ষণ হচ্ছে…",
  cancel: "বাতিল",
  edit: "সম্পাদনা",
  pause: "বিরতি দিন",
  resume: "আবার চালু করুন",
  complete: "শেষ হয়েছে",
  delete: "মুছুন",
  deleteConfirm: "এই Reminder স্থায়ীভাবে মুছে ফেলবেন?",
  snoozeTenMinutes: "১০ মিনিট পরে মনে করান",
  skipOccurrence: "এবারটি বাদ দিন",
  completeOccurrence: "এবারের কাজ শেষ",
  snoozed: "Reminder ১০ মিনিট পিছিয়ে দেওয়া হয়েছে।",
  skipped: "এবারের Reminder বাদ দেওয়া হয়েছে।",
  occurrenceCompleted: "এবারের কাজ সম্পন্ন হয়েছে।",
  next: "পরবর্তী",
  noNext: "পরবর্তী সময় নেই",
  preferencesTitle: "Notification পছন্দ",
  preferencesDescription:
    "প্রতিটি বিষয়ের channel এবং নীরব সময় server-side প্রয়োগ হয়।",
  preview: "Lock screen preview",
  minimal: "শুধু সাধারণ ইঙ্গিত",
  hidden: "শুধু নতুন Notification বলুন",
  enabled: "চালু",
  quietStart: "শুরু",
  quietEnd: "শেষ",
  savePreferences: "পছন্দ সংরক্ষণ করুন",
  pushTitle: "Web Push",
  pushDescription:
    "অনুমতি চাইবার আগে কী হবে তা জেনে নিন। Browser অনুমতি না দিলেও Focused চলবে।",
  pushUnsupported: "এই Browser-এ Web Push সমর্থিত নয়।",
  pushNotConfigured: "এই environment-এ Web Push এখনো configure করা হয়নি।",
  enablePush: "এই ডিভাইসে চালু করুন",
  enablingPush: "অনুমতি নেওয়া হচ্ছে…",
  permissionDenied:
    "Browser Notification permission বন্ধ রেখেছে। Browser settings থেকে চালু করতে হবে।",
  testPush: "Test Notification পাঠান",
  revoke: "ডিভাইস সরান",
  device: "এই ডিভাইস",
  loading: "Notification প্রস্তুত হচ্ছে…",
  signIn: "Notification দেখতে আগে sign in করুন।",
  signInAction: "Sign in",
  loadError: "Notification এখন দেখানো যাচ্ছে না। আবার চেষ্টা করুন।",
  changedElsewhere: "অন্য session-এ তথ্য বদলেছে। নতুন অবস্থা দেখানো হয়েছে।",
  saved: "পরিবর্তন সংরক্ষিত হয়েছে।",
  pushEnabled: "এই ডিভাইসে Web Push চালু হয়েছে।",
  testSent: "Test Notification পাঠানো হয়েছে।",
  offline: "আপনি offline আছেন—সর্বশেষ সংরক্ষিত অবস্থা দেখানো হচ্ছে।",
  weekdays: ["রবি", "সোম", "মঙ্গল", "বুধ", "বৃহস্পতি", "শুক্র", "শনি"],
  categories: {
    reminder: "Reminder",
    focus: "Focus Session",
    habit: "অভ্যাস",
    goal: "লক্ষ্য",
    planning: "পরিকল্পনা",
    system: "System ও নিরাপত্তা",
  } satisfies Record<NotificationCategory, string>,
} as const;

const en = {
  eyebrow: "Calm and timely",
  title: "Notifications and Reminders",
  subtitle:
    "Receive only what matters now. Private details never appear on the lock screen.",
  refresh: "Refresh",
  unread: (count: number) => `${count} unread`,
  activeReminders: "Active reminders",
  pushDevices: "Web Push devices",
  quietHours: "Quiet hours",
  inboxTitle: "Notification inbox",
  inboxDescription: "Recent meaningful updates, without unnecessary noise.",
  inboxEmpty: "There are no notifications. Important updates will appear here.",
  markRead: "Mark read",
  markUnread: "Mark unread",
  archive: "Archive",
  remindersTitle: "Your reminders",
  remindersDescription: "Create and control one-time or recurring reminders.",
  remindersEmpty: "No reminders yet. Start with one small next action.",
  addReminder: "Add reminder",
  editReminder: "Edit reminder",
  titleLabel: "What should we remind you about?",
  titlePlaceholder: "For example: Start today's main task",
  noteLabel: "Details (optional)",
  notePlaceholder: "This is visible only inside the app",
  frequency: "Schedule",
  once: "Once",
  daily: "Daily",
  weekly: "Selected days",
  date: "Date",
  time: "Time",
  interval: "Every number of days",
  channels: "Delivery channels",
  inApp: "In app",
  webPush: "Web Push",
  save: "Save",
  saving: "Saving…",
  cancel: "Cancel",
  edit: "Edit",
  pause: "Pause",
  resume: "Resume",
  complete: "Complete",
  delete: "Delete",
  deleteConfirm: "Permanently delete this reminder?",
  snoozeTenMinutes: "Remind me in 10 minutes",
  skipOccurrence: "Skip this occurrence",
  completeOccurrence: "Complete this occurrence",
  snoozed: "Reminder snoozed for 10 minutes.",
  skipped: "This reminder occurrence was skipped.",
  occurrenceCompleted: "This occurrence is complete.",
  next: "Next",
  noNext: "No upcoming time",
  preferencesTitle: "Notification preferences",
  preferencesDescription:
    "Category channels and quiet hours are enforced on the server.",
  preview: "Lock-screen preview",
  minimal: "Show a generic prompt",
  hidden: "Only say a notification arrived",
  enabled: "Enabled",
  quietStart: "Starts",
  quietEnd: "Ends",
  savePreferences: "Save preferences",
  pushTitle: "Web Push",
  pushDescription:
    "Understand what happens before granting permission. Focused still works if permission is denied.",
  pushUnsupported: "Web Push is not supported by this browser.",
  pushNotConfigured: "Web Push is not configured in this environment.",
  enablePush: "Enable on this device",
  enablingPush: "Requesting permission…",
  permissionDenied:
    "Browser notification permission is blocked. Enable it in browser settings.",
  testPush: "Send test notification",
  revoke: "Remove device",
  device: "This device",
  loading: "Preparing notifications…",
  signIn: "Sign in to view notifications.",
  signInAction: "Sign in",
  loadError: "Notifications are unavailable right now. Try again.",
  changedElsewhere:
    "The data changed in another session. The latest state is shown.",
  saved: "Changes saved.",
  pushEnabled: "Web Push is enabled on this device.",
  testSent: "The test notification was sent.",
  offline: "You are offline. Showing the latest saved state.",
  weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  categories: {
    reminder: "Reminders",
    focus: "Focus sessions",
    habit: "Habits",
    goal: "Goals",
    planning: "Planning",
    system: "System and security",
  } satisfies Record<NotificationCategory, string>,
} as const;

export type NotificationCopy = typeof bn | typeof en;
